name: 🚜 Sync Bot
on:
  schedule:
    - cron: '*/30 * * * *' # Every 30 mins
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests supabase
      - name: Run
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          JUPITER_API_KEY: ${{ secrets.JUPITER_API_KEY }}
        run: python sync_bot.py
